const nodemailer = require('nodemailer');

const transporter = nodemailer.createTransport({
  service: 'gmail',
  auth: {
    user: process.env.EMAIL_USER,
    pass: process.env.EMAIL_APP_PASSWORD,
  },
});

async function sendLeadNotification({ name, phone, email, company, serviceNeeded, message, source, clientName, notificationEmail }) {
  const recipient = notificationEmail || process.env.NOTIFICATION_EMAIL || process.env.EMAIL_USER;
  const sender = process.env.EMAIL_USER;

  const html = `
<!DOCTYPE html>
<html>
<body style="margin:0;padding:0;background:#f1f5f9;font-family:Arial,sans-serif;">
<table width="100%" cellpadding="0" cellspacing="0" style="background:#f1f5f9;padding:32px 0;">
  <tr><td align="center">
    <table width="560" cellpadding="0" cellspacing="0" style="background:#ffffff;border-radius:12px;overflow:hidden;box-shadow:0 2px 8px rgba(0,0,0,.08);">
      <tr><td style="background:#1e3a5f;padding:24px 28px;">
        <h1 style="margin:0;color:#fff;font-size:20px;">⚡ ElectricLead Pro</h1>
        <p style="margin:4px 0 0;color:#93c5fd;font-size:13px;">New Web Lead — ${clientName || 'Chat Widget'}</p>
      </td></tr>
      <tr><td style="padding:24px 28px 0;">
        <div style="background:#dbeafe;border-left:4px solid #3b82f6;border-radius:4px;padding:10px 14px;margin-bottom:20px;">
          <strong style="color:#1d4ed8;">New lead from your website chat widget!</strong>
        </div>
        <h2 style="margin:0 0 12px;font-size:14px;color:#1e3a5f;border-bottom:2px solid #e2e8f0;padding-bottom:6px;">👤 Contact Details</h2>
        <table width="100%" cellpadding="6" cellspacing="0">
          <tr><td style="color:#64748b;font-size:12px;width:120px;">Name</td><td style="font-weight:600;font-size:13px;">${name || '—'}</td></tr>
          <tr><td style="color:#64748b;font-size:12px;">Phone</td><td style="font-weight:600;font-size:13px;">${phone || '—'}</td></tr>
          <tr><td style="color:#64748b;font-size:12px;">Email</td><td style="font-weight:600;font-size:13px;">${email || '—'}</td></tr>
          <tr><td style="color:#64748b;font-size:12px;">Company</td><td style="font-weight:600;font-size:13px;">${company || '—'}</td></tr>
          <tr><td style="color:#64748b;font-size:12px;">Service</td><td style="font-weight:600;font-size:13px;">${serviceNeeded || '—'}</td></tr>
          <tr><td style="color:#64748b;font-size:12px;">Source</td><td style="font-weight:600;font-size:13px;">${source || 'Web chat'}</td></tr>
        </table>
      </td></tr>
      ${message ? `
      <tr><td style="padding:20px 28px 0;">
        <h2 style="margin:0 0 12px;font-size:14px;color:#1e3a5f;border-bottom:2px solid #e2e8f0;padding-bottom:6px;">💬 Message</h2>
        <div style="background:#f8fafc;border-radius:6px;padding:12px;font-size:13px;color:#374151;line-height:1.7;">${message}</div>
      </td></tr>` : ''}
      <tr><td style="padding:24px 28px;text-align:center;color:#94a3b8;font-size:11px;">
        <p style="margin:0;">Generated by <strong>ElectricLead Pro</strong> · ${new Date().getFullYear()}</p>
      </td></tr>
    </table>
  </td></tr>
</table>
</body>
</html>`;

  await transporter.sendMail({
    from: `"${clientName || 'ElectricLead Pro'}" <${sender}>`,
    to: recipient,
    subject: `New Web Lead: ${name || 'Unknown'} — ${serviceNeeded || 'General Inquiry'}`,
    html,
  });

  console.log(`✅ Web lead email sent to ${recipient}`);
}

module.exports = { sendLeadNotification };