const nodemailer = require('nodemailer');

function esc(str) {
  return String(str || '').replace(/&/g,'&amp;').replace(/</g,'&lt;').replace(/>/g,'&gt;').replace(/"/g,'&quot;').replace(/'/g,'&#39;');
}

// Single source of truth for where internal notifications land.
const NOTIFICATION_EMAIL = process.env.NOTIFICATION_EMAIL || 'office@mintt.ca';

const transporter = nodemailer.createTransport({
  service: 'gmail',
  auth: {
    user: process.env.EMAIL_USER,
    pass: process.env.EMAIL_APP_PASSWORD,
  },
});

async function sendLeadNotification({ name, phone, email, company, serviceNeeded, message, source, clientName, notificationEmail }) {
  const recipient = notificationEmail || NOTIFICATION_EMAIL;
  const sender = process.env.EMAIL_USER;

  // Escape all user-controlled fields before HTML interpolation
  const _name    = esc(name);
  const _phone   = esc(phone);
  const _email   = esc(email);
  const _company = esc(company);
  const _service = esc(serviceNeeded);
  const _source  = esc(source);
  const _message = esc(message);
  const _client  = esc(clientName);

  const html = `
<!DOCTYPE html>
<html>
<body style="margin:0;padding:0;background:#f1f5f9;font-family:Arial,sans-serif;">
<table width="100%" cellpadding="0" cellspacing="0" style="background:#f1f5f9;padding:32px 0;">
  <tr><td align="center">
    <table width="560" cellpadding="0" cellspacing="0" style="background:#ffffff;border-radius:12px;overflow:hidden;box-shadow:0 2px 8px rgba(0,0,0,.08);">
      <tr><td style="background:#1e3a5f;padding:24px 28px;">
        <h1 style="margin:0;color:#fff;font-size:20px;">⚡ ElectricLead Pro</h1>
        <p style="margin:4px 0 0;color:#93c5fd;font-size:13px;">New Web Lead — ${_client || 'Chat Widget'}</p>
      </td></tr>
      <tr><td style="padding:24px 28px 0;">
        <div style="background:#dbeafe;border-left:4px solid #3b82f6;border-radius:4px;padding:10px 14px;margin-bottom:20px;">
          <strong style="color:#1d4ed8;">New lead from your website chat widget!</strong>
        </div>
        <h2 style="margin:0 0 12px;font-size:14px;color:#1e3a5f;border-bottom:2px solid #e2e8f0;padding-bottom:6px;">👤 Contact Details</h2>
        <table width="100%" cellpadding="6" cellspacing="0">
          <tr><td style="color:#64748b;font-size:12px;width:120px;">Name</td><td style="font-weight:600;font-size:13px;">${_name || '—'}</td></tr>
          <tr><td style="color:#64748b;font-size:12px;">Phone</td><td style="font-weight:600;font-size:13px;">${_phone || '—'}</td></tr>
          <tr><td style="color:#64748b;font-size:12px;">Email</td><td style="font-weight:600;font-size:13px;">${_email || '—'}</td></tr>
          <tr><td style="color:#64748b;font-size:12px;">Company</td><td style="font-weight:600;font-size:13px;">${_company || '—'}</td></tr>
          <tr><td style="color:#64748b;font-size:12px;">Service</td><td style="font-weight:600;font-size:13px;">${_service || '—'}</td></tr>
          <tr><td style="color:#64748b;font-size:12px;">Source</td><td style="font-weight:600;font-size:13px;">${_source || 'Web chat'}</td></tr>
        </table>
      </td></tr>
      ${_message ? `
      <tr><td style="padding:20px 28px 0;">
        <h2 style="margin:0 0 12px;font-size:14px;color:#1e3a5f;border-bottom:2px solid #e2e8f0;padding-bottom:6px;">💬 Message</h2>
        <div style="background:#f8fafc;border-radius:6px;padding:12px;font-size:13px;color:#374151;line-height:1.7;">${_message}</div>
      </td></tr>` : ''}
      <tr><td style="padding:24px 28px;text-align:center;color:#94a3b8;font-size:11px;">
        <p style="margin:0;">Generated by <strong>ElectricLead Pro</strong> · ${new Date().getFullYear()}</p>
      </td></tr>
    </table>
  </td></tr>
</table>
</body>
</html>`;

  await transporter.sendMail({
    from: `"${clientName || 'ElectricLead Pro'}" <${sender}>`,
    to: recipient,
    subject: `New Web Lead: ${name || 'Unknown'} — ${serviceNeeded || 'General Inquiry'}`,
    html,
  });

  console.log(`✅ Web lead email sent to ${recipient}`);
}

// ── CUSTOMER CONFIRMATION (Mintt-branded) ──
// Sent to the person who submitted info via the chatbot/web form.
async function sendCustomerConfirmation({ name, email, serviceNeeded }) {
  const sender = process.env.EMAIL_USER;
  const firstName = esc(name ? String(name).trim().split(/\s+/)[0] : 'there');
  const _service = esc(serviceNeeded);

  const html = `
<!DOCTYPE html>
<html>
<body style="margin:0;padding:0;background:#f1f5f9;font-family:Arial,sans-serif;">
<table width="100%" cellpadding="0" cellspacing="0" style="background:#f1f5f9;padding:32px 0;">
  <tr><td align="center">
    <table width="560" cellpadding="0" cellspacing="0" style="background:#ffffff;border-radius:12px;overflow:hidden;box-shadow:0 2px 8px rgba(0,0,0,.08);">
      <tr><td style="background:#00c96b;padding:28px;text-align:center;">
        <h1 style="margin:0;color:#fff;font-size:24px;letter-spacing:-.02em;">Mintt</h1>
        <p style="margin:6px 0 0;color:#d1fae5;font-size:14px;">We've received your message!</p>
      </td></tr>
      <tr><td style="padding:32px 28px;">
        <p style="font-size:16px;font-weight:600;color:#1e293b;margin:0 0 16px;">Hi ${firstName},</p>
        <p style="font-size:14px;color:#374151;line-height:1.7;margin:0 0 20px;">
          Thanks for reaching out to <strong>Mintt</strong>! We've received your information and a member of
          our team will be in touch with you <strong>within 24 hours</strong>.
        </p>
        ${_service ? `
        <div style="background:#ecfdf5;border:1px solid #a7f3d0;border-radius:8px;padding:16px;margin-bottom:20px;">
          <p style="margin:0 0 6px;font-size:12px;font-weight:700;color:#047857;text-transform:uppercase;letter-spacing:.05em;">What you're looking for</p>
          <p style="margin:0;font-size:14px;font-weight:600;color:#065f46;">${_service}</p>
        </div>` : ''}
        <p style="font-size:14px;color:#374151;line-height:1.7;margin:0 0 24px;">
          Have a question in the meantime? Reach us anytime at
          <strong>office@mintt.ca</strong> or <strong>647-559-8674</strong> — we're happy to help.
        </p>
        <p style="font-size:14px;color:#374151;margin:0;">
          Talk soon,<br/>
          <strong>The Mintt Team</strong>
        </p>
      </td></tr>
      <tr><td style="background:#f8fafc;padding:16px 28px;text-align:center;border-top:1px solid #e2e8f0;">
        <p style="margin:0;font-size:11px;color:#94a3b8;">Mintt · office@mintt.ca · 647-559-8674</p>
      </td></tr>
    </table>
  </td></tr>
</table>
</body>
</html>`;

  await transporter.sendMail({
    from: `"Mintt" <${sender}>`,
    to: email,
    subject: `Thanks for reaching out, ${firstName}! — Mintt`,
    html,
  });

  console.log(`✅ Customer confirmation sent to ${email}`);
}

// ── SIGNUP WELCOME (Mintt-branded) ──
// Sent to a new paying customer right after they create an account.
async function sendSignupWelcome({ companyName, email, plan }) {
  const sender = process.env.EMAIL_USER;
  const _company = esc(companyName);
  const _plan = esc(plan ? String(plan).charAt(0).toUpperCase() + String(plan).slice(1) : '');

  const html = `
<!DOCTYPE html>
<html>
<body style="margin:0;padding:0;background:#f1f5f9;font-family:Arial,sans-serif;">
<table width="100%" cellpadding="0" cellspacing="0" style="background:#f1f5f9;padding:32px 0;">
  <tr><td align="center">
    <table width="560" cellpadding="0" cellspacing="0" style="background:#ffffff;border-radius:12px;overflow:hidden;box-shadow:0 2px 8px rgba(0,0,0,.08);">
      <tr><td style="background:#00c96b;padding:28px;text-align:center;">
        <h1 style="margin:0;color:#fff;font-size:24px;letter-spacing:-.02em;">Mintt</h1>
        <p style="margin:6px 0 0;color:#d1fae5;font-size:14px;">Welcome aboard! 🎉</p>
      </td></tr>
      <tr><td style="padding:32px 28px;">
        <p style="font-size:16px;font-weight:600;color:#1e293b;margin:0 0 16px;">Welcome${_company ? `, ${_company}` : ''}!</p>
        <p style="font-size:14px;color:#374151;line-height:1.7;margin:0 0 20px;">
          Thanks for signing up with <strong>Mintt</strong>. Your account is all set and ready to go.
        </p>
        ${_plan ? `
        <div style="background:#ecfdf5;border:1px solid #a7f3d0;border-radius:8px;padding:16px;margin-bottom:20px;">
          <p style="margin:0 0 6px;font-size:12px;font-weight:700;color:#047857;text-transform:uppercase;letter-spacing:.05em;">Your plan</p>
          <p style="margin:0;font-size:14px;font-weight:600;color:#065f46;">${_plan}</p>
        </div>` : ''}
        <p style="font-size:14px;color:#374151;line-height:1.7;margin:0 0 24px;">
          You can log in anytime to view your leads and dashboard. If you need a hand getting started,
          just reply to this email or reach us at <strong>office@mintt.ca</strong> or <strong>647-559-8674</strong>.
        </p>
        <p style="font-size:14px;color:#374151;margin:0;">
          Glad to have you,<br/>
          <strong>The Mintt Team</strong>
        </p>
      </td></tr>
      <tr><td style="background:#f8fafc;padding:16px 28px;text-align:center;border-top:1px solid #e2e8f0;">
        <p style="margin:0;font-size:11px;color:#94a3b8;">Mintt · office@mintt.ca · 647-559-8674</p>
      </td></tr>
    </table>
  </td></tr>
</table>
</body>
</html>`;

  await transporter.sendMail({
    from: `"Mintt" <${sender}>`,
    to: email,
    subject: 'Welcome to Mintt 🎉',
    html,
  });

  console.log(`✅ Signup welcome sent to ${email}`);
}

module.exports = { sendLeadNotification, sendCustomerConfirmation, sendSignupWelcome };
